# Workflow ka naam
name: Analyze and Build Debug APK

# Yeh workflow kab chalega: jab 'main' branch mein code push hoga
on:
  push:
    branches: [ main ]

jobs:
  build:
    # Kis machine par chalega
    runs-on: ubuntu-latest

    steps:
      # Step 1: Aapke repo ka code download karega
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Java (JDK) set up karega
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Flutter environment set up karega
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Step 4: Flutter dependencies install karega
      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Code ko analyze karega
      - name: Run Code Analysis
        run: flutter analyze

      # Step 6: Code ki formatting check karega (naya Dart command)
      - name: Check Code Formatting
        run: dart format --output=none --set-exit-if-changed .

      # Step 7: Debug APK build karega (Bina signing ke)
      - name: Build Debug APK
        run: flutter build apk --debug

      # Step 8: Build hui APK file ko "Artifacts" mein upload karega
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
